on:
  push:
    branches-ignore:
      - "master"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Output versions
        run: |
          git --version
          node --version
          npm --version
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
      - name: Tests check
        run: npm run test:unit